version: 2
updates:
  # Root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Apps
  - package-ecosystem: "npm"
    directory: 
    - "/client"
    - "/client/turborepo/apps/www"
    - "/client/turborepo/apps/vendor"
    - "/client/turborepo/apps/admin"
    - "/client/turborepo/packages/ui"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"