version: 2
updates:
  # Root
  - package-ecosystem: "npm"
    directory: "/" # root directory
    schedule:
      interval: "weekly"

  # Apps
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/turborepo/apps/www"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/turborepo/apps/vendor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/turborepo/apps/admin"
    schedule:
      interval: "weekly"

  # Packages
  - package-ecosystem: "npm"
    directory: "/client/turborepo/packages/ui"
    schedule:
      interval: "weekly"